packages:
  - apps/*
  - functions
  - packages/*

engineStrict: true
saveWorkspaceProtocol: rolling
sharedWorkspaceLockfile: true
disallowWorkspaceCycles: true

allowBuilds:
  '@firebase/util': true
  protobufjs: true
  re2: true
